/* SPDX GPL-2 Danny Milosavljevic <dannym@scratchpost.org> */

#ifndef __DT_BINDINGS_TSS463AA_H__
#define __DT_BINDINGS_TSS463AA_H__

#define TSS463AA_DIAGNOSTIC_MODE_RXD0 0
#define TSS463AA_DIAGNOSTIC_MODE_RXD2 1
#define TSS463AA_DIAGNOSTIC_MODE_RXD1 2
#define TSS463AA_DIAGNOSTIC_MODE_AUTO 3

/* RNW, RTR, CHTx, CHRx */
#define TSS463AA_MESSAGE_TYPE_TRANSMIT_MESSAGE 0
#define TSS463AA_MESSAGE_TYPE_RECEIVE_MESSAGE 4
#define TSS463AA_MESSAGE_TYPE_IMMEDIATE_IN_FRAME_REPLY_MESSAGE 8
#define TSS463AA_MESSAGE_TYPE_DEFERRED_REPLY_MESSAGE 9
#define TSS463AA_MESSAGE_TYPE_PROBE_REPLY_REQUEST_MESSAGE 10
#define TSS463AA_MESSAGE_TYPE_REPLY_REQUEST_MESSAGE 12

#endif /* __DT_BINDINGS_TSS463AA_H__ */
